# Generated by Django 3.2.12 on 2024-06-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.PositiveSmallIntegerField()),
                ('class_name', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('room_number', models.PositiveSmallIntegerField()),
                ('class_size', models.PositiveSmallIntegerField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('school_year', models.IntegerField()),
                ('created_at', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
